# Generated by Django 5.2.14 on 2026-05-14 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО / Название')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('referral', 'Рекомендация'), ('ads', 'Реклама'), ('social', 'Соцсети'), ('other', 'Другое')], default='other', max_length=16, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('qualified', 'Квалифицирован'), ('converted', 'Конвертирован'), ('rejected', 'Отказ')], default='new', max_length=16, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_leads', to='clients.client', verbose_name='Клиент после конвертации')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['full_name'], name='leads_lead_full_na_267cf9_idx')],
            },
        ),
    ]
