# Generated by Django 5.2.14 on 2026-05-25 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка')),
                ('condition_code', models.CharField(max_length=50, verbose_name='Код условия')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Звонок'), ('email', 'Email'), ('meeting', 'Встреча'), ('note', 'Заметка'), ('message', 'Сообщение')], default='note', max_length=16, verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Взаимодействие с лидом',
                'verbose_name_plural': 'Взаимодействия с лидами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(verbose_name='Балл до')),
                ('score_after', models.IntegerField(verbose_name='Балл после')),
                ('reason', models.CharField(choices=[('new', 'Новый лид'), ('new_interaction', 'Новое взаимодействие'), ('time_decay', 'Таймер'), ('manual', 'Вручную'), ('data_change', 'Изменение данных')], max_length=32, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Лог скоринга',
                'verbose_name_plural': 'Логи скоринга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
            ],
            options={
                'verbose_name': 'Бейдж менеджера',
                'verbose_name_plural': 'Бейджи менеджеров',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('deals_closed', models.IntegerField(default=0, verbose_name='Закрыто сделок')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Выручка')),
                ('avg_response_min', models.FloatField(default=0, verbose_name='Среднее время реакции (мин)')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Конверсия (%)')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Статистика менеджера',
                'verbose_name_plural': 'Статистика менеджеров',
                'ordering': ['-month', '-points'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-score', '-created_at'], 'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Потенциальная сумма (₽)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый контакт'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('hot', '🔥 Горячий'), ('warm', '🟡 Тёплый'), ('cold', '🔵 Холодный')], default='cold', max_length=8, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='lead',
            name='response_speed_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость ответа клиента (ч)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0, verbose_name='AI-скоринг'),
        ),
        migrations.AddField(
            model_name='lead',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скоринг обновлён'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='leads_lead_priorit_ddce28_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-score'], name='leads_lead_score_a9af9b_idx'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead', verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='leadscorelog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='leads.lead', verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='managerachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.achievement', verbose_name='Достижение'),
        ),
        migrations.AddField(
            model_name='managerachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='managerstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_stats', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterUniqueTogether(
            name='managerachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='managerstats',
            unique_together={('user', 'month')},
        ),
    ]
