# Generated by Django 5.2.14 on 2026-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_achievement_leadinteraction_leadscorelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город / Регион'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_size',
            field=models.CharField(blank=True, choices=[('solo', 'Самозанятый / ИП'), ('small', '2–10 человек'), ('medium', '11–50 человек'), ('large', '51–200 человек'), ('enterprise', '200+ человек')], max_length=16, verbose_name='Размер компании'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('any', 'Любой')], max_length=16, verbose_name='Предпочтительный способ связи'),
        ),
        migrations.AddField(
            model_name='lead',
            name='deal_urgency',
            field=models.CharField(blank=True, choices=[('immediate', 'Срочно (до 1 недели)'), ('month', 'В этом месяце'), ('quarter', 'В этом квартале'), ('year', 'В этом году'), ('unknown', 'Не определено')], default='unknown', max_length=16, verbose_name='Срочность сделки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'IT / Технологии'), ('retail', 'Розничная торговля'), ('manufacturing', 'Производство'), ('finance', 'Финансы / Банки'), ('real_estate', 'Недвижимость'), ('healthcare', 'Здравоохранение'), ('education', 'Образование'), ('construction', 'Строительство'), ('logistics', 'Логистика / Транспорт'), ('food', 'Общепит / Продукты'), ('beauty', 'Красота / Здоровье'), ('other', 'Другое')], max_length=20, verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего контакта'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Доп. телефон'),
        ),
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_interest',
            field=models.TextField(blank=True, help_text='Что ищет клиент, какая задача', verbose_name='Интерес / Потребность'),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram',
            field=models.CharField(blank=True, help_text='@username или номер телефона', max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт компании'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО / Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки / Комментарии'),
        ),
    ]
