# Generated by Django 5.2.14 on 2026-06-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_city_lead_company_size_lead_contact_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Потенциальная сумма (₸)'),
        ),
    ]
