# Generated by Django 5.2.14 on 2026-05-13 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_won', models.BooleanField(default=False, verbose_name='Финальный — успех')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Финальный — отказ')),
                ('color', models.CharField(default='#0d6efd', help_text='HEX-цвет для шапки колонки', max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Этапы воронки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('won', 'Успех'), ('lost', 'Отказ')], default='open', max_length=10, verbose_name='Статус')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата закрытия')),
                ('notes', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client', verbose_name='Клиент')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
    ]
